### ISSUE TITLE
Support for conda envs

### ISSUE THREAD

**Issue by RonaldOellers** [caozhichongchong/QuickVariants#2]
Hey, I am new to adding .jar files to a conda env. 

From your README, you seem to not have packaged it into any of the repositories. How would you add this to a conda env? or otherwise bind into a workflow? I want to test wether this might perform better in my pipeline that bcftools call.

Thank you for this very interesting new tool!

**Comment by caozhichongchong** [comment]
Hi,

Interesting question.

You can activate your conda environment where you intend to run QuickVariants.
Then you can install java by `conda install conda-forge::openjdk`
After installation, you can execute the QuickVariants JAR file you downloaded from [here](https://github.com/caozhichongchong/QuickVariants/releases) by running
`java -jar quick-variants.jar <arguments>`
Please let us know if you have any questions.
Thank you.

**Comment by RonaldOellers** [comment]
Hey, I would look to see if I can put it into a snakemake workflow, so I need to be able to have a environment defined where it is installed in. Ideally automatically via eg. a conda env.yml. The running part seems clear and easy to use

**Comment by mathjeff** [comment]
Thanks everybody! I think this is done now
